# -*- coding: utf-8 -*-
"""Mental Health Library

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Ui_ANHrLSQvo0_KMtVfQx6ojZB793fXB
"""

from datetime import datetime
import time     
import random
from matplotlib import pyplot as plt
import numpy as np

def pleh(): #resources for help
  time.sleep(3)  
  help = input("tell us what we can add to make this project better: ")
  time.sleep(3)  
  print('''
If the resources on this project, are not enough for you. Here are a list of websites, textlines 
and hotlines that can help you. What you're feeling won't last forever. You can, and will get through it.

Websites:
www.suicidepreventionlifeline.org
www.sptsusa.org/teens
www.trevorproject.org (LGBTQ+)
www.ItGetsBetter.org (LGBTQ+)

Text Messages:
Crisis Textline: Text HOME to 741741
TeenLine: Text TEEN to 839863 between 6pm-9pm PST
TrevorText: Text START to 678678

Hotline:
National Suicide Prevention
1-800-273-TALK (8255)

Teen Line
310-855-4673 6pm to 10pm PST

YouthLine
877-968-8491

National Suicide Hotline
1-800-SUICIDE (784-2433)

Trevor lifeline (LGBTQ+)
1-866-488-7386

Trans Lifeline
US: (877) 565-8860
CANADA: (877) 330-6366
''') 
def pos(): #positive affirmations
  aff = ["I know things may feel owerwhelming but I'm proud of you and how well you're coping", "it's ok to prioritise yourself, you deserve to do this", "I understand anxiety can make you question things, but this is a reminder to not question you matter", "please be patient and gentle with yourself, you're doing better than you think you are"]
  print(random.choice(aff))

def form(): #defining the function of form to add to each section
  print('''
  In case, you would like some help dealing with this, we are here to help you out, 
    kindly fill the follwing form to book a consultation with a mental health expert.''') 
  time.sleep(3) #adding delays at every step
  form = input("Do you wish to fill the form? (yes/no): ")    
  if form == "yes" or form == "Yes" or form == "YES":
    print("Form:")
    time.sleep(3)
    name = input("Please enter your name: ")

    time.sleep(3)
    DoB = input("Please enter your date of birth:  (ensure that it follows the format DD/MM/YY) ")
    ldob = len(DoB) #ensuring that the format is followed
    while ldob != 8:
      print('This is an invalid format, kindly follow the format that has been provided')
      DoB = str(input("Please enter your date of birth:  (ensure that it follows the format DD/MM/YY) "))
      ldob = len(DoB)
      
    time.sleep(3)
    phone = input('please enter your phone number: ')
    digitno = len(phone)
    while digitno != 10 or not phone.isnumeric() : 
      print(' ERROR this no. is not valid please enter a 10 digit no')
      phone = input('please enter your phone number: ') #ensuring phone number is 10 digit long
      digitno = len(phone)

    time.sleep(3)
    date = input("What date would work for you to meet with us: ")
    ldate = len(date)  #ensuring that the format is followed
    while ldate != 8:
      print('This is an invalid format, kindly follow the format that has been provided')
      DoB = str(input("What date would work for you to meet with us:  (ensure that it follows the format DD/MM/YY) "))
      ldate = len(date)

    today = time.strftime("%d/%m/%y") #today's date 
    dateToday = datetime.strptime(today, '%d/%m/%y').date() 

    dateIn = datetime.strptime(date, '%d/%m/%y').date()
    while dateIn<dateToday: #comparing today's date to enterred date 
 
      print("Invalid date.") #ensuring date enterred is valid 
      date = input("What date would work for you to meet with us: ")
      dateIn = datetime.strptime(date, '%d/%m/%y').date()
    else:
      exit()

    time.sleep(3)
    Time = input("What time would work for you: (enter 24 hour format) ") #time in 24 hour format
    d = datetime.strptime(Time, "%H:%M")
    d.strftime("%I:%M %p")

    time.sleep(3)
    comm = input("""Anything else you would like us to know about:  """)
    time.sleep(3)
    print("We will ensure that the same is taken care of. ")

    time.sleep(3)
    print(''' 
          Here's a copy of your form response: ''') #copy of form responses
    dic = {"Name":name, "Date of Birth":DoB, "Contact Number":phone}
    for key,value in dic.items():
      print(key, ':', value)
    print("We will meet on", date, 'at',d.strftime("%I:%M %p"))
    print("This is what we'll take care of :",comm)
    print("Thank you :)) We hope to see you soon")
    print('''Please find our contact information below: 
+91 88775 51122
+91 99885 54466
sanyaaneja10@gmail.com
ishitaduggal22@gmail.com
''')
def end():
  time.sleep(3)  
  pos()
  form()
  pleh()

print("""Welcome to the mental health library!  
We are here to support you in what you are going through - 
to help you understand more about it  or help you understand 
what someone you know might be going through and provide you 
with the necessary resources and understanding to help combat it.""") #intro

time.sleep(3)  
while True:
  print(''' Main Menu:
  1. Anxiety
  2. Depression
  3. Family
  4. Grief
  5. Bullying
  6. LGBTQ+
  7. Managing emotions
  8. Self Help
  9. Getting Unstuck
  10. Student Life
  11. Forgiveness
  12. I just don't feel okay.
  13. Other
  
  Enter 0 to exit''') #menu

  time.sleep(3)
  x = int(input("Enter your Choice: "))

  while x > 13 or x < 0: #program still running even if invalid number enterred
    print(' ERROR please enter a valid choice ')
    x = int(input("Enter your Choice: "))

  if x == 1 : #anxiety 
    print(''' ANXIETY :

  Things that you didn't know were anxiety:
1. feeling unable or too scared to speak up 
2. worrying about every word choice you use while interacting with people 
3. thinking everyone can see inside your head
4. beleiving everyone is silently judging you
5. thinking you had to be perfect to avoid judgement 
6. critising your every movement 
7. feeling like you had to overachieve and be the best at everything and know everything to be considered intelligent
8. not wanting to come off as stupid
9. resenting yourself for not living up to everyone's standards
10. feeling like you constantly might mess everything up
11. obsessing over the tiniest detail
12. getting irritated easily, when people or situations don't go according to plan
13. having trouble falling asleep even when you're tired
14. feeling overwhelmed by a list of small tasks
15. obsessively thinking the same thoughts over and over again
16. physical symptoms like upset stomach, hot flashes
17. nervous habits like biting your lips or nails
18. worrying over others' feelings when they hurt you
19. unable to enjoy the moment
20. difficulty asking things
21. feeling like everything is too much to process
22. always imagining the worst outcomes
23. replaying past actions and conversations in your head
24. thinking it's always your fault
25. comparing yourself with others
26. seeking extra reassurance because you doubt yourself
27. delay replying to messages for days
28. cancelling plans last minute

what is important to remember here is that these negative emotions are not who you are 
that everything you are feeling is not real 
it is just your anxiety and it will be ok.

How to cope with anxiety: 
1. Write out your emotions: Be honest with how you feel and then push yourself to write about your emotions and feelings. 
Grab your journal and get more aligned with your emotions
2. Move around: When you are feeling anxious and can’t seem to reduce your anxiety just get up and move around. 
3. Acknowledge things in your control: It’s important to acknowledge everything in your control rather than the things you can’t. 
Manage your anxiety by keeping the positive things in front of your mind as a reminder that things aren’t all bad.
4. Listen to music: 
5. Do something that you feel comfortable with to distract yourself, try making art, writing, whatever speaks to you.
6. Be around someone you can talk to, who calms you down and helps you through what you're feeling.
7. Deep Breathing: Breathe in slowly through your nose into your abdomen and allow your abdomen to expand fully. 
Now breathe out slowly through your mouth, or your nose, whatever feels more natural. Repeat this 15-20 times or until you calm down.
8. Drinking a hot beverage: 
9. Exercising: 
10. Interrupting your anxious thought process by instead thinking "what if things do work out", "what if the worst doesn't happen"
Explore the best case scenario or the "better" case scenario
11. Read out loud: 
12. Take a social media break:
13. Get good rest
14. Sushi train metaphor: practising the sushi train metaphor, helps in understanding to not develop on these thoughts 
but instead accept that they come and go. https://www.youtube.com/watch?v=tzUoXJVI0wo

Here's a suggestion: Check your stress levels and check them frequuently. 
Make a list of activities that bring those levels down and then make the time 
to do those things. Your needs matter all the time.
''')
    time.sleep(3)
    quiz = input('''confused between your anxiety and intuition?
take the quiz to find out which one you’re really feeling 
(start/stop)''')
#anxiety or intuition quiz #wnrs
    if quiz == "start" or quiz == "START" or quiz == "Start":
      print("is it anxiety or intuition? A Quiz.")
      print("")

      count = 0
      anti = 0

      react = input('''i’m reacting to:
(a) a painful hypothetical scenario
(b) the present moment ''')
      print("")
      if react == "a":
        count +=1
      else:
        anti +=1

      feel = input('''my body feels:
(a) tense, constricted, heart racing
(b) calm, relaxed, centered ''')
      print("")
      if feel == "a":
        count +=1
      else:
        anti +=1

      thought = input('''my thoughts feel:
(a) intrusive
(b) reassuring ''')
      print("")
      if thought == "a":
        count +=1
      else:
        anti +=1

      anxious = input('''i’m anxious / have a sense of dread:
(a) most of the day
(b) rarely ''')
      print("")
      if anxious == "a":
        count +=1
      else:
        anti +=1

      pattern = input('''my thought pattern is more of a
(a) constant “what if”
(b) moment of knowing ''')
      print("")
      if pattern == "a":
        count +=1
      else:
        anti +=1

      chaos = input('''my thoughts are:
(a) chaotic and hard to explain
(b) clear and reasonable ''')
      print("")
      if chaos == "a":
        count +=1
      else:
        anti +=1

      if count>anti:
        print('''YOUR ANXIETY IS LYING TO YOU!!!

Anxiety and intuition often feel similar. They are NOT the same. 
Simply having the awareness that your anxious thoughts are NOT reality is the first step towards healing. 
Take 3 deep breaths and remember… you are bigger than what is making you anxious.
''')
  
      elif count==anti:
        print('''EMOTIONS ARE MESSY!!! AND THAT'S OKAY!!

Anxiety and intuition often feel similar. They are NOT the same. 
Simply having the awareness that your anxious thoughts are NOT reality is the first step towards healing. 
Take 3 deep breaths and remember… you are bigger than what is making you anxious.
''')

      else:
        print('''YOUR INTUITION IS TELLING YOU SOMETHING!!!

Intuition is trying to tell you something. Are you listening? 
Don’t ignore what’s right in front of you just because you don’t want to see it. 
Accepting your truth is the first step towards healing.
''')

    else:
      exit()
  
    list = []
    l2 = []
    l3 = []
    l4 = []
    l5 =[]

    time.sleep(3)
    print('''here's an exercise to help you ground yourself 
''')

    time.sleep(3)
    for i in range(1,6):
      see = input("describe 5 things you can see ")
      list.append(see)

    print(" ") 
    print(list)
    print(" ")

    time.sleep(3)
    for i in range(1,5):
      feel = input("describe 4 things you can feel ")
      l2.append(feel)

    print(" ")
    print(l2)
    print(" ")
  
    time.sleep(3)
    for i in range(1,4):
      hear = input("describe 3 things you can hear ")
      l3.append(hear)

    print(" ")
    print(l3)
    print(" ")

    time.sleep(3)
    for i in range(1,3):
      smell = input("describe 2 things you can smell ")
      l4.append(smell)

    print(" ")
    print(l4)
    print(" ")

    time.sleep(3)
    for i in range(1,2):
      taste = input("describe 1 thing you can taste ")
      l5.append(taste)

    print(" ")
    print(l5)
    print(" ") 
  
    time.sleep(3)
    print('''how you can you help someone with anxiety:
1. Learn their triggers: Learn to look for "warning signs" that they are feeling trapped, and ask if they are alright or need to talk. 
Learn to look out for what's wrong and create a space for them to share their struggles.
2. Get permission before you touch them: If they’re freaking out, don’t touch them unless you ask and get explicit permission. 
Anxiety and panic attacks are often accompanied by hypersensitivity. Sometimes that hug or consoling shoulder rub just makes things 
twice as bad.
3. Remove them from a stressful situation: If you’re out in public and they start feeling anxious, remove them from the situation if possible. 
Sometimes the atmosphere is overwhelming or creates an uncomfortable environment. Distractions also help.
4. Invent a ritual: If they're having a panic attack, try doing something with them that might help calm them down, 
like counting backwards from 100. You can do the even numbers and they can do the odd ones.
5. Let it be about them: Don’t try to compare their anxiety to yours, or say “I know how you feel” if you really don’t. 
It may seem helpful, but it can be insulting for a person with legitimate anxiety problems to hear about how you know what they’re going through 
just because you also tend to get stressed out during finals. Don’t take the legitimacy out of their problem by making it about you.
6. Give them an outlet: Suggest or buy them a journal to write, it's another way to vent. Or buy them a colouring book with some gel pens. 
Anything that they can express themselves through. 
7. Let them know you still like them: Remind them that you still like them. A little text reminder like, “Hey, thought of you with X thing I saw today,” 
or, “Hey, excited to see you this weekend!” Anxiety can make you question things, such as if you matter to the people around you. A small reminder 
goes a long way. 
8. Make plans and keep them: Having social anxiety can mean that it's hard to initiate plans, and sometimes it's even hard to accept them 
because they feel like they should give you an out in case you were only including them to be polite – no matter how close or how old the friendship is. 
So just keep inviting them. They do love you and want to see you!
9. But give them an escape clause: When making or even just suggesting plans, always leave CLEAR room for an out. Now or later. Ongoing. 
There’s nothing better for an anxious person than knowing they can bail out of a plan without you hating them. Or them hating themselves.
10. Walk them through a plan in advance: They might find it helpful when someone else takes control of the situation and time. 
Say “Look, here’s what we’re going to do. Here’s the plan, step by step and here’s what’s going to happen in an hour.” 
And then everyone else has to be like, “Yep, sounds good, let’s go.” Then the anxious person won’t have to worry about a) the plan or b) if everyone else is happy.
11. Make them feel heard: Acknowledge their fears and anxiety as real things. Let them know that you hear them, and are there for them – IF they want you there. 
Because, for some, you being there can also be too much.
12. Get some fresh air with them: Encourage them to take a walk outside with you. Being outside mey help them remember there are bigger things 
than what they're worrying about. There’s also room to run or walk off that anxious energy.
13. Just be with them, and bring their favourite things: Ask if there is anything you can do – if they say no then go grab them a favourite book 
or movie and a big blanket and just be with them.
14. Text back: Don’t leave them hanging in communication. They tend to play a thousand scenarios in their head while waiting to hear back. 
Do them a favour and let them know you’re thinking and will get back to them.
15. Call them: Call them on a regular schedule for a check-in. It doesn’t have to be a long intimate conversation every time. 
It could be as simple as, “How was your day? How are you feeling? Have you been worrying about anything?”, and then done.
16. And send an end-of-the-day “I love you” text: The simple gesture to let the person experiencing anxiety know they are loved 
and cared for is bigger than you might realize.
17. Find a creative way to check in: Sometimes it's hard to answer somehting as simple as "how are you" or "what are you going through",
so try something a little different. For example: use a colour chart to know how the other is doing, choose colours to represent if they 
feel calm or anxious. 
18. Let them take the lead: Let them take the lead. Give them space if they need it and don’t follow them around but try remaining accessible, 
in a nearby room or keeping your phones on if they need you. When they're feeling better, ask them questions about why they were feeling that way, 
or what worked and what didn’t work. It’s important to understand that sometimes they're not sure what will help, 
so give them the chance to try different things. 
19. Record a calming voicemail they can play any time: Don't try to fix them or their problems, but instead try recording a voicemail for them to listen to 
every time they feel anxious. The best thing you can do for them is help them get out of a stressful situation; take them somewhere else, even if it’s just on a little walk.
20. Help them make a plan: When you're with them during a situation where they might be experincing their anxiety, try focussing on things you can do right that instant 
to help them alleviate their anxiety. Breathing exercises, grounding etc. Then, you start making a plan for the things they can do that day to make progress on whatever 
is stressing them out (job, relationship, money, whatever). They have to let you know whenever they complete those tasks, and when they do, appreciate them for following through
and how those tasks helped her. It’s all about celebrating little victories.
21. Let them know you’re right there with them: The worst part of panic attacks can be feeling completely isolated and alone, which is incredibly scary, 
and what can help is having someone make sure to let them know that they aren’t alone. So, long story short, if you have a friend who is having a panic attack
or anxiety attack, make sure they know you’re there for them. Whether that means holding their hand (if they’re OK with it) or talking with them or just being 
near them, let them know they are not alone and that they don’t have to deal with this alone. 
22. Make them feel normal: Sometimes instead of having a conversation about it, or help dealing with it, they might just want you to continue to act normal.
23. Make time to do nothing with them: It’s easy to become involved in your own life, but just taking the time to wander around the grocery shop together is simple and nice.
24. And talk about ridiculous things: Be a listening ear. Even though anxiety can make them sound like a broken record, just listening to them tell you about the things 
that bring on anxiety and how it affects them is helpful. Take walks with them and talk about the universe, alternate dimensions, or your plan in the event of a zombie apocalypse. 
Getting them out of their own head for a while is wonderfully relaxing.
25. Help them with the little things: It’s incredibly helpful for them when you do stuff that might be really simple and easy, but is something that makes them uncomforrtable,
like ordering at a restaurant. 
26. Know what makes them laugh: Sometimes they just need you to tell them it’s all in their head. But for the tougher times, try doing something that is incredibly random and 
wierd that they might enjoy. 
27. And know what makes them feel calm: Stay calm, be patient, acknowledge that the anxiety is a real thing, but reassure them that the moment will pass and that you will be there 
supporting them until it does. Bring up topics that you know are calming for the person, remind them to breathe. If it’s a close friend or partner, you can hold their hand 
or rub their arm or leg. Just keep them aware and in the moment.
28. Call up good memories: Bring up a happy memory you had together and instead of just talking about it outright leave out certain details and get them to fill them in. 
As a result they would focus more on the details and fill in the story, not even realizing their anxiety would become easier to deal with.
29. Never underestimate a good cup of tea: Try making a cup of tea for them, and just creating a warm atmosphere around them that makes them feel safe and comfortable.
30. Or a great soundtrack: You can queue up music that you know would help calm them down (they might have a playlist of their own), all the while being there 
but staying silent unless they need and ask you to do otherwise.
31. Bring the fun to them: Understand that sometimes they may not be able to go out, and be willing to make allowances. Take a bottle of wine and a DVD to their home, 
make cocktails in the kitchen, have a baking day or just a cup of coffee and a chat. If they aren’t up to leaving, bring the fun to them – 
just because they are uncomfortable in spaces doesn’t mean they don’t want to enjoy themselves. Also understand they may seem clingy if they are particularly anxious – 
it’s probably just because they always expect worst-case scenario. 
32. Stick with them: Don’t abandon them. With anxiety, a lot of people tend to stop asking them do to things with them, and that hurt so much. 
Be a true friend and hold their hand – physically, metaphorically, or both. 
33. Listen: Just listen. That’s the best you can do for anyone who is struggling with anxiety. Listen to what they’re telling you, believe them, and do not blame yourself. 
When they're at their most anxious, they want to be alone. It’s difficult to explain to someone you love that you want them to go away.
34. Be the person they want to talk to about their anxiety: Be there and support them no matter what. Help them work on ways to cope that you can practise together. 
Be the person they want to talk to about their anxiety.
35. And always, always, ask: Never assume anything – don’t assume they need a hug, because they might want space, and don’t assume they want to be left alone, 
because maybe they would like some company. Ask what you can do and what you shouldn’t do when they are going through an attack, for example. 
You can always offer a shoulder to cry on, a listening ear, an honest opinion, breathing with them… But really, it all melts down to ask, and actually listen.
''') #helping someone with anxiety

  elif x == 2 : #depression
    print('''DEPRESSION:

Depression isn't just sadness or having suicidal thoughts. 
Many, many, people function with depression that doesn't even really feel sad. 
It just feels empty. It feels like not caring. It feels like complete mental exhaustion.

Depression can also look like:
1. Feeling fatigued and exhausted all the time.
2. Lack of interest in things you used to love.
3. Inability to motivate yourself to complete 
simple tasks.
4. difficulty sleeping or sleeping too much.
5. No interest in food. Loss of apetite, over-eating.
6. Sabotaging good things because you feel unworthy. 
7. Hopelessness towards the future. No long term plans.
8. Inability to feel or identify emotions.
9. Isolating yourself from friends and family.

When you're depressed , the phrase "it gets better" can feel like a cliche. 
But we still say it because its true - it does get better. You can be happy again, 
you can get through whatever you're going through. There are better things coming.

Depression has many faces. There are times when it's hard to brush your teeth or hair 
or shower and there are times when you've looked completely fine, even happy, on the outside.

It can be really frustrating when someone in your life is depressed. You want them to snap out of it, 
you want to be able to help or make it better. Be kind. Help where you can. Listen. Be supportive. Love them. 
Encourage them to get help. Provide resources if you can. But mostly, just love them. They're trying as hard as they can.

Here's the difference between what you see and what they may be feeling, 
to help you understand their experience better:
1. Uncaring - They care, but it's hard to show it. They feel like a burden or they're numb.
2. Pessimistic - Looking on the bright side doesn't make depression better
3. Weak - It takes so much to get through the day. They're doing their best.
4. Lazy - They want to contribute but they feel frozen or drained of energy.
5. Difficult - They're trying to get better but it's hard to fight the right treatment.
6. Sadness - It's not sad. It's hopeless, numb, empty. drained. Complete despair.
7. Dramatic - Depression doesn't always make sense. They can't snap out of it.
8. Fine - They don't always look depressed but they're still struggling inside.
10. Unhygenic - They put themselves last to take care of other responsibilities.
They're trying. 

Unfortunately our resources for the same are limitied, but here are a few resources we have referred to 
while making our project that can help you. Consulting your doctor is an important part of the process, 
sometimes self help on its own is not enough.

@realdepressionproject on instagram
https://www.selfloverainbow.com
''') #helping someone else #difference b/w what you see and what happens #what it looks like

  elif x == 3 : #family
    print(''' FAMILY:
  Here are some common family problems that you may be going through:

1. Constant Arguments:
Disagreements are normal. After all, we all have our own opinions. 
However, when healthy communication falters and discussions increasingly become 
arguments, a solution must be found. Whether with your spouse or your children,
arguments can seriously raise tensions in the family. Depending on the 
severity of the disagreement, they can even permanently damage relationships. 

2. Being far from the family:
Distance, because of work or other reasons, can be a strain on an otherwise 
healthy relationship. And if you have kids, it can be challenging to be away 
from them for an extended period of time, especially if you have to travel 
often. Many times, being away from the family during holidays is especially 
hard and it is okay, everyone gets homesick from time to time.

3. Schedule mismatch:
It is hard enough to get yourself organized, now you have a family to take 
care of. When you have a partner and kids to manage, chaos is inevitable. 
And, sometimes it ends up badly. Especially as a parent, it may seem as if you 
have no time. Your schedule may be cluttered with work, chores, and your 
children’s events, leaving little time for the things you want to do.

4. Clashing personalities:
It's far from uncommon for a family to have clashing personalities. 
Perhaps siblings don't get along with one another, or one child doesn't get 
along with one or both parents. This can go a big step further when you're 
dealing with someone who displays narcissistic tendencies or other toxic traits,
which introduces a bunch of other issues into the family unit, such as 
gaslighting or explosive fighting.

5. Monetary issues:
A significant stressor in many family’s lives, financial troubles can add 
significant tension to any household. So many families will deal with challenges 
surrounding finances, budgeting, and employment. Money problems can include one
parent making all the money and feeling burdened, not having enough basic 
funds for what you need, generational issues around poverty or gambling, 
and so much more. Money touches most areas of our life, and if there are 
issues here, the effects will be felt within any family.

6. Mental illness within the family:
If a parent (or even a child) is dealing with mental health issues or addiction, 
that can cause a huge rift within a family unit. When one of the family members 
is suffering from mental illness, it is one of the hardest family issues to 
handle. It is a serious issue and it can affect the family members with high 
intensity. But, these people need your support the most.

7. Divorce:
Divorce destroys a family. It is one of the really ugly family issues. 
The family structure is surely disturbed because of this.It's not uncommon, 
but yes, divorce certainly does disrupt a family unit and can cause problems 
when it's swept under the rug. It is surprising how many people haven't processed 
divorce in the family. It really does impact how you see relationships, 
and models fears around relationships, and often people don't even talk about 
it in the family.

8. Lack of communication:
It is fine when you are interested in making yourself clear to a colleague. 
But, you must not take the same practise at home. When there is miscommunication 
among family members, a lot of things go wrong. Communication is the issue of 
every relationship. 

9. Parental pressure:
Perfectionism within a family can have extremely negative effects on children 
and their self-worth.When parents shame or dictate how children should feel 
or be, it can take a toll on their ability to grow as individuals. Parents do 
need to have some boundaries but not when it gets to the point where it's 
emotionally abusive.
 ''' )
    prob = int(input('Enter your specific probolem: '))

    if prob == 1:
      print('''
Sometimes, in a relationship, it is all about how you are arguing instead of 
what you are arguing about.So, it is better to stay calm, take a step back, 
and wait for the negative vibes to leave the room. If you are arguing with the 
same intensity as the other person, then there is no handling such family issues.

Whether with your spouse or your children, arguments can seriously raise tensions 
in the family. Depending on the severity of the disagreement, they can even 
permanently damage relationships. Therefore, it is critical to handle arguments 
with care, not allowing heightened emotions to get the better of you. Instead, 
focus on the problem at hand, and ask yourself: “Why does this person believe 
what they believe?” If you can find a way to understand the other person, you 
can create a foundation to build upon.

If the argument has turned into a fight and anyone is feeling overwhelmed, call 
a time-out and return to the conversation later. Arguments don’t have to be a 
bad thing—they are natural after all. And they can be perfectly manageable if 
everyone tries their hardest to be respectful and come to some sort of consensus.
 
In case this problem still persists, you may wish to get help. If you choose to do so,
we are here for you. Kindly fill the following form to book a counselling session with 
one of our professionals.
 ''') 

    elif prob == 2: 
      print('''
Getting homesick can happen at any time.It is natural and even a good thing because
it is an evidence to how much you love your family.
You can video chat with them, talk to them most of the time to get rid of this 
homesickness. Make good friends around you who make you feel at home.Play online 
games together, or sync up movies to watch together. In the digital age, 
there are many solutions to make distance easier to manage.
  
Problems with distance arise not only from having too much distance, but also from 
not having enough distance. The media perpetuates the myth that if two people 
love each other, they can happily spend every minute of their time together. 
While this fantasy might play out well in the first months of dating, 
any serious relationship needs space. This problem is not limited to time 
spent with your significant other. Parents, especially stay-at-home parents, 
can also feel cooped up after too much time with their kids.

The solution? Get out of the house, or carve out some alone time. Try to involve 
yourself in fun and exciting hobbies and passions that you can do on your own.
  
In case this problem still persists, you may wish to get help. If you choose to do so,
we are here for you. Kindly fill the following form to book a counselling session with 
one of our professionals.
  ''')

    elif prob == 3:
      print('''
Another common family issue is scheduling conflicts. If one or more family 
members has a busy schedule, it can be hard to connect together and make time
for each other. This can look like one parent who works long hours and is rarely
home during the day, or issues with scheduling as children get more involved 
with extracurriculars.
  
One solution is to use a calendar or daily schedule system. This way you can 
prioritize what matters most. You can also try to make an agreement with 
neighbors or friends to watch each other’s kids once a week. No need to be hard 
on yourself or the family. Just understand that the quality time that you 
spend with each other matters the most. So, take out some time for them as well.
  
  ''')
    elif prob == 4:
      print('''
It can your wife, husband, siblings, kids, or anyone who is the source of your 
stress when you just enter the house. Personal clashes are always stressful and tough. 
Sometimes, they drive us crazy.

If you have some of these members at home, it is better to be ready before you 
enter the home. It hurts to face the surprising conflict than to be already 
ready for it. Give yourself time and understand that they are not going to change.
  ''')

    elif prob == 5:
      print('''
A few general tips for better money management are to create a zero-based budget, 
cut out unnecessary purchases, and to keep at least few months’ expenses in a 
liquid form of savings. In terms of changing your perspective on money, it is 
helpful to look at money as a means to get the goods and services you want, not 
as an end in and of itself.

As the things you accumulate may not provide as much happiness as you think, 
one way to make some quick cash and free up your space as well is to sell 
unnecessary belongings your family has accumulated. Financial problems can test 
relationships, but if you are open to creative problem solving together, 
you will get through them.
  ''')

    elif prob == 6:
      print('''
There are a number of ways you can help a friend, relative or colleague who has a mental health problem:
Talking to someone is often the first step to take when you know they are going through a hard time. 
This way you can find out what is troubling them and what you can do to help.

1. Set time aside with no distractions:
t is important to provide an open and non-judgemental space with no distractions.

2. Let them share as much or as little as they want to:
Let them lead the discussion at their own pace. Don’t put pressure on them to tell you anything 
they aren’t ready to talk about. Talking can take a lot of trust and courage.
You might be the first person they have been able to talk to about this.

3. Don't try to diagnose or second guess their feelings:
You probably aren’t a medical expert and, while you may be happy to talk and offer support, you aren’t a trained counsellor. 
Try not to make assumptions about what is wrong or jump in too quickly with your own diagnosis or solutions.

4. Keep questions open ended:
ay "Why don’t you tell me how you are feeling?" rather than "I can see you are feeling very low". 
Try to keep your language neutral. Give the person time to answer and try not to grill them with too many questions.

5. Talk about wellbeing:
Talk about ways of de-stressing or practicing self-care and ask if they find anything helpful. 
Exercising, having a healthy diet and getting a good nights sleep can help protect mental health and sustain wellbeing. 

6. Listen carefully to what they tell you:
Repeat what they have said back to them to ensure you have understood it. 
You don’t have to agree with what they are saying, but by showing you understand how they feel, 
you are letting them know you respect their feelings.

7. Offer them help in seeking professional support and provide information on ways to do this:
You might want to offer to go the GP with them, or help them talk to a friend or family member. 
Try not to take control and allow them to make decisions.

8. Know your limits:
Ask for help or signpost if the problem is serious. If you believe they are in immediate danger 
or they have injuries that need medical attention, you need to take action to make sure they are safe. 

If you believe this is only working to a small extent, why not get them the mental health they deserve?
Fill in the form below to book a counselling session.



''')
    elif prob == 7:
      print('''
Divorce is difficult for everyone. The family structure is surely disturbed because of this. 
But, you must be there for your family and give them an ear or shoulder to cry one. 
You must not lash out on them or leave them at this hour of need.  
  ''')

    elif prob == 8:
      print('''
If you are having trouble clearing things out, you must talk to them and sort out a solution. 
It is always better to communicate better than to miscommunicate.
What if we didn’t fill in the gaps with the worst possible version of events? 
What if we made the intentional choice to assume the best about a situation when the information was missing? 
What if we went a step further and actually asked our partners to tell us what they mean rather than trying to read their minds? 
  
When we find ourselves hurt, we can allow the hurt to serve as an invitation to deeper understanding.

Ask yourself if there might be other explanations for something your partner did that might give them the benefit of the doubt.

Create Space for Intentional Communication

In case these tips don't seem to be working, it is better to talk a professional regarding this. 
Kindly fill the form below to talk to one of our mental health experts regarding this.
''')

    elif prob == 9:
      print('''
Finding a balance between your parents/carers’ expectations of you and your own desires can feel like a constant battle. 
If they want you to take one path and you’re set on another, you might be feeling stuck between a rock and a hard place.

First up, it’s important to remember that you're all good, just as you are. 
What you choose to do with your life is important, but it doesn’t define your value as a person. 
It can help to work out what your strengths are. 
  
It’s not a big deal that you and your parents have different ideas and expectations. 
What matters is how you solve with the situation. Their expectations are usually coming from the right place, 
they just want you to succeed or be happy. It might just be that their idea of what that looks like is very different from yours. 
Or, it might be related to their expectations of themselves.
If you think the bar they are setting is way too high, try talking to them about how it makes you feel. 
It can help to acknowledge this (even just to yourself).

Even if you follow all the tips above, your parents/carers might still be disappointed with the choices you make. 
If so, remember that there are probably other areas of your life that they’re stoked about.

Remember, we are there for you, in case you require external help in dealing with this,
fill out the following form to book a counselling session with one of our mental health experts.
  ''')

    else:
      print('Error, this is an invalid choice, Please try again.')

  elif x == 4 : #grief
    print( ''' GRIEF:
  
  Grief is hard.
There is no easy way to accept the death of someone you love and just move on, 
it’s never that easy, but you’ve got to keep moving forward. You have to go 
through the grieving process, feel your feelings, and allow yourself to keep 
going.

Allow Yourself to Feel
It’s so tempting to find some way to numb yourself, to turn off the faucet 
of emotion and give yourself a break from the onslaught of pain – don’t. 
Although the pain of losing someone you love can be excruciating, you must 
allow yourself to feel.

Shutting yourself off to your own feelings can stop you from moving forward 
with your life.

People who refuse to deal with their feelings are often left depressed, anxious 
and unable to enjoy any part of life. You may feel every emotion in the book 
before starting to feel any resemblance of normality, but you’re entitled to 
feel however you do.

A Good Support Group
There will be times when you’ll just feel like shutting yourself away and 
dealing with your grief by yourself. But there will be other times when you 
need people around you.

Whether its friends cooking your meals or family getting together to share 
thoughts and feelings, it will all help you to process. You need to remember 
to take care of yourself, but grief can make you feel like you don’t want to 
do daily tasks, like showering, eating or going outside.

There are also support groups that are based on chronic or 
terminal illnesses that will give you a gentle nudge, love, and acceptance.

There’s No One Rule for All
Many people go through a similar grieving process: denial, anger, bargaining, 
depression and eventually acceptance. However, everyone is different, and you 
shouldn’t expect to feel the same way as others.

Grief is a cycle – you will probably go through it multiple times, get stuck 
in several stages, and repeat parts of it when you least expect it. 
Allow yourself to go with it.

Rediscover Life
When you come out of the fog of grief, so many things feel different. 
It can almost feel like learning to walk again. You have to rediscover 
an appreciation for life. You have to rediscover what your life now looks 
like without that peson.

Unfortunately, there are many people who feel like their lives ended with 
their loved ones, especially in the grief of a spouse or child. But no loved 
one would want you to stop living your life.

It can be difficult to move on without them. Remember there are so many 
wonderful things left to experience in the world. Making plans you can look 
forward to is a great first step towards dealing with a death in a positive way. 
For instance, why not plan a trip to somewhere you’ve always wanted to go to? 
Perhaps you and your loved one discussed it in the past or maybe there’s a special 
somewhere your loved one wanted their ashes scattered. No matter where you go or 
what you do, it’s important to start somewhere.

Dealing with the death of a loved one can seem impossible, but you will come 
out the other side. 

how to cope with grief after it's been some time:
1. Talk about your grief. Don't worry about bringing anyone down. You're allowed to grieve
and you're allowed to talk about it.
2. Create boundaries with your time. If you need to take time for yourself - do that.
3. Find a way to honor them. Start a new tradition that celebrates their memory.
4. Set realistic espectations. You will probably be sad, angry, or upset and that's okay.
5. Allow yourself to feel all of your emotions. Resentment and anger are normal emotions.
6. Check-in with your needs. Reach out for hugs. Let people know you need extra love.
''') #how to cope

  elif x == 5 : #bullying
    print(''' BULLYING:
Bullying is a huge issue today that affects a lot of people, more children than adults but still is a humongous problem.
Most children or adults today will claim that they have been bullied in recent times or the past. 
It is a horrible issue that children have to deal with and the stress of it is almost unnatural, especially for young, schoolgoing minds.
 
IMPACTS OF BULLYING:
1. It can make children not wanto to go outside to play.

2. It can make school feel like HELL! It is hard to keep your mind on schoolwork when you are aware that you are probably
going to be teased in some time.

3. Bullying bothers everyone, not just the people being bullied but teachers and guardians as well.

4. It often cause the victim to lose interest in things they once used to enjoy.

5. It drastically increases the chances of one either being or acquiring a mental illness in the present of future.

6. Bullying is most often Traumatizing for the victim, it distorts one's sense of self--respect and self-esteem.

7. It can potentially make someone feel 'Suicidal' and commit 'Self Harm' (In case you feel so, immediately get help by contacting one of the helplines stated in the beginning.)

8. Victims of bullying often reports major disruptions in their daily lifestyle as well like changes in eating habits,
disrupted sleep and recurring nightmares.

HOW TO DEAL WITH BULLIES:
There are multiple ways of getting yourself out of this rut, even though it wasn't your choice to be bullied and it isn't your fault in any way
that you are going through this. Know that we, as a community are with you. There are ways to catch hold and control of the situation and take action 
regarding this.
Here are some ways you might be able to deal with your bullies:

1. Don't give the bully a chance. As much as you can, avoid the bully. 
You can't go into hiding or skip class, of course. But if you can take a different route and avoid the mean kid, do so.

2. Stand tall and be brave. When you're scared of another person, you're probably not feeling your bravest.
But sometimes just acting brave is enough to stop a bully. 
How does a brave person look and act?
Stand tall and you'll send the message: "Don't mess with me." It's easier to feel brave when you feel good about yourself. See the next tip! 

3. Feel good about you. Nobody's perfect, but what can you do to look and feel your best? Maybe you'd like to be more fit. 
If so, maybe you'll decide to get more exercise, watch less TV, and eat healthier snacks. 
Or maybe you feel you look best when you shower in the morning before school. If so, you could decide to get up a little earlier 
so you can be clean and refreshed for the school day.

4. Get a buddy (and be a buddy). Two is better than one if you're trying to avoid being bullied. 
Make a plan to walk with a friend or two on the way to school, recess, lunch, or wherever you think you might meet the bully. 
Offer to do the same if a friend is having bully trouble. 
Get involved if you see bullying going on in your school — tell an adult, stick up for the kid being bullied, and tell the bully to stop.


Hopefully these tips will help you stand up for yorself and/or avoid the bully whenever possible.
In case, you need a little more help dealing with this, fill the form bellow to book a counselling session with a mental healthy expert.
:)  ''')

  elif x == 6 : #LGBTQ
    print('''LGBTQ+ : 
    ''') 
    pronouns = input("Hello, My pronouns are... ")
    print("it's ok if you haven't figured them out yet ")
    time.sleep(3)
    print('''
Wherever you are in your coming out journey
Wherever you have been you are completely valid in your sexuality.

Sometimes, the hardest person to come out to is yourself. It takes a lot of battling internalized homophobia and fighting your demons but eventually you'll got there.
There is no timeline for when you should come out. Take your time. and also, you don’t even have to label yourself to be valid as queer or to celebrate how far you’ve come! 

Reminding you if you’re going through something similar we see you, you are not alone, we're proud of you and you deserve to celebrate yourself just as much as any of the rest of us.

If you’re newly out, whether that be to everyone you know, only a couple people or simply yourself, 
welcome to the community! we’re so proud of you <3

How to support someone who comes out to you:
1. Hold space for them to talk about their feelings. 
2. Validate their experience.
3. Ask how they are feeling
4. Acknowledge their courage for telling you. 
5. Don't assume their experience is the same as everyone else's. 
6. Ask respectful questions to understand their needs.
7. learn more about the LGBTQ+ community.
8. let them come out to others on their own terms.
9. Thank them for trusting you. 
10. Ask what you can do to support them. 
11. Remind them you will always be there for them. 
12. Treat them the same way you always have.
13. Tell them you love them. your words matter.
14. Show continous love and support through your actions. 

Remmeber everyone's coming out experince is different. 
There is no one way to come out and there is no one right way to show support.

Supporting someone who's changed their pronouns:
1. Use their new pronouns. Interchange them if they go by multiple pronouns.
2. If you make a mistake. Correct yourself, even if they don't say anything.
3. Avoid attention on a mistake. Apologise once, correct yourself, and move on.
4. Ask if they're cofortable with you using their new pronouns with others.
5. Kindly help correct others when you hear pronouns being misused.
6. Celebrate! Assure them that they have your respect and support.

Respecting pronouns impacts mental health outcomes within the LGBTQ+ community. Affirming LGBTQ youth’s gender 
by using pronouns that align with their gender identity has been shown to improve mental health outcomes.

The Trevor Project found that LGBTQ+ youth who reported having their pronouns respected by all or most of 
the people in the lives attempted suicide at HALF THE RATE of those who did not have their pronouns respected.

Respecting someone’s pronouns is an easy way to be an ally but more importantly, shows respect and indicates 
a safe space for LGBTQ+ individuals. 

In the same way we don’t question people for their names, pronoun use should be treated the same.

a great way to start is by offering your own pronouns when you meet someone: 

“Hi, I’m  Carol and my pronouns are they/them. What are yours?”
    ''')

  elif x == 7: #managing emotions #inside out identifying emotions exercise 
    print(''' MANAGING EMOTIONS:
Before you are able to manage your emotions, you have to accept your emotions. Before acceptance,
it is important to identify and acknowledge them. To get here, you have to honest with yourself.
It is ok to feel whatever you are.

Here's an exercise to make identifying your emotions easier for you, 
do you remember the movie Inside Out, and the characters representing Riley's emotions:
Joy, Sadness, Fear, Anger, and Disgust. Let's try simplifying our emotions to the 5 of these
and depict them.
''')
    time.sleep(3)
    sad = input("how would you describe how sad you feel today in percent ")
    time.sleep(3)
    joy = input("how would you describe how happy you feel today in percent ")
    time.sleep(3)
    dis = input("how would you describe how disgusted you feel today in percent ")
    time.sleep(3)
    ang = input("how would you describe how angry you feel today in percent ")
    time.sleep(3)
    fear = input("how would you describe how afraid you feel today in percent ")
    time.sleep(3)
    print("")

  # Creating dataset
    emo = ['sadness', 'joy', 'disgust',
        'anger', 'fear']
 
    data = [sad, joy, dis, ang, fear]
 
  # Creating plot
    fig = plt.figure(figsize =(10, 7))
    plt.pie(data, labels = emo)
 
  # show plot
    plt.show()
    print("")
  
    questions = ["when was the last time you felt sad ", "when was the last time you felt happy ", "when was the last time you felt afraid ", "when was the last time you felt angry ", "when was the last time you felt digusted "]
    q3 = ["what do you do on days you feel sad ", "what do you do on days you feel angry "]
  
    time.sleep(3)
    q1 = input(random.choice(questions))
    time.sleep(3)
    q2 = input("what made you feel this way ")
    time.sleep(3)
    Q3 = input(random.choice(q3))
    time.sleep(3)
    q4 = input("what is something small that makes you feel happy ")
    print("")
  
    time.sleep(3)
    sad2 = input("how would you describe how sad you feel right now in percent ")
    time.sleep(3)
    joy2 = input("how would you describe how happy you feel right now in percent ")
    time.sleep(3)
    dis2 = input("how would you describe how disgusted you feel right now in percent ")
    time.sleep(3)
    ang2 = input("how would you describe how angry you feel right now in percent ")
    time.sleep(3)
    fear2 = input("how would you describe how afraid you feel right now in percent ")
    print("")

  # Creating dataset
    emo2 = ['sadness', 'joy', 'disgust',
        'anger', 'fear']
 
    data = [sad2, joy2, dis2, ang2, fear2]
 
  # Creating plot
    fig = plt.figure(figsize =(10, 7))
    plt.pie(data, labels = emo2)
 
  # show plot
    plt.show()
    print("")

    time.sleep(3)
    Q1 = input("why do you feel diiferent now? ")
    time.sleep(3)
    Q2 = input("what emotions do you feel more now? ")
    time.sleep(3)
    Q = input("what made you feel this way ")
    time.sleep(3)
    Q4 = input("what emotions can you feel less now? ")
    time.sleep(3)
    Q5 = input("what made you feel this way ")

    time.sleep(3)
    print('''When you notice your mood getting worse, ask yourself, 'What's going through my mind right now?' 
Here's a process to help you navigate through them.''') #automatic thoughts record

    time.sleep(3)
    situation = input('''What lead to the unpleasant emotion? 
What distressing physical sensations did you have?''')
    time.sleep(3)
    a_thoughts = input('''What thoughts or image(s) went through your mind?
How much did you believe the thought at the time (0-100%)?''')
    time.sleep(3)
    emotion = input('''What emotion(s) did you feel at the time?
How intense was the emotion (0-100%)?''')
    time.sleep(3)
    print('''Questions to compose an adaptive respone:
(1) What is the evidence that the automatic thought is true?
(2) Is there an alternative explanation?
(3) What's the worst that could happen? 
What's the best that could happen? 
What's the most realistic outcome?
(4) If a friend were in and this situation and had this thought, 
what would i tell him/her?''')
    time.sleep(3)
    a_response = input('''What thinking styles did you engage in?
Use questions below to respond to the automatic thoughts
How much do you believe each response (0-100%)?''')
    time.sleep(3)
    outcome = input('''How much do you now believe your Automatic Thoughts (0-100%)?
What emotions do you now feel? At what intensity?''')
  
  elif x == 8: #self help
    print(''' SELF HELP:

If you don't feel ready to reach out for help, that's ok. Here are a few ways you can help yourself when you don't feel ok.

Below are the unhelpful thinking styles that we adopt, when we're in a stressful situation. 
Understanding what they are, learning to not believe them, and adopting healthy ways to cope can be helpful. 

1. All-or-nothing thinking: Describes thinking or acting in extremes. Sometimes called ‘black and white thinking’.
For example, If I’m not perfect I have failed. Either I do it right or not at all.
2. Overgeneralization: Seeing a pattern based upon a single event, or being overly broad in the conclusions we draw.
For example, Everything is always rubbish. Nothing good ever happens. 
3. Mental filter or selective abstraction: Describes only paying attention to certain types of evidence.
For example, Noticing our failures but not seeing our successes.
4. Disqualifying the positive: Discounting the good things that have happened or that you have done for some reason or another.
For example, ‘writing off ’ positive events as a ‘fluke’ or saying that they don’t count.
5. Jumping to conclusions: “arbitrarily jumping to a negative conclusion that is not justified by the facts”. 
With the ‘fortune telling’ variant we imagine and predict that bad things will happen to us. 
With the ‘mind reading’ variant we assume that other people are thinking negatively about us.
6. Magnification and minimization: Describe how we exaggerate imperfections and errors while minimising achievements and strengths.
7. Emotional reasoning: Describes the process of taking one’s emotions as evidence of truth.
For example, feeling hopeless and concluding that a problem is therefore impossible to solve.
8. “Should” statements: Reflect our (often unreasonable) standards (“I should do this”, “I must do that”) 
and frequently lead to feelings of frustration, shame, or guilt - 
Using critical words like ‘should’, ‘must’, or ‘ought’ can make us feel guilty, or like we have already failed.
If we apply ‘shoulds’ to other people the result is often frustration.
9. Labeling and mislabeling: Describes the process of 'summing up' ourselves or others by labeling ourselves with tags
such as, "I am hopeless" or "I am stupid".
10. Personalization and blame: describe occasions when you conclude – arbitrarily – that what happened was your fault even 
when you were not responsible. Conversely, blaming other people for something that was your fault.  
  ''')
    time.sleep(3)
    print('''When you notice your mood getting worse, ask yourself, 'What's going through my mind right now?' 
Here's a process to help you navigate through them.''')
  
    time.sleep(3)
    situation = input('''What lead to the unpleasant emotion? 
What distressing physical sensations did you have?''')
    time.sleep(3)
    a_thoughts = input('''What thoughts or image(s) went through your mind?
How much did you believe the thought at the time (0-100%)?''')
    time.sleep(3)
    emotion = input('''What emotion(s) did you feel at the time?
How intense was the emotion (0-100%)?''')
    time.sleep(3)
    print('''Questions to compose an adaptive respone:
(1) What is the evidence that the automatic thought is true?
(2) Is there an alternative explanation?
(3) What's the worst that could happen? 
What's the best that could happen? 
What's the most realistic outcome?
(4) If a friend were in and this situation and had this thought, 
what would i tell him/her?''')
    time.sleep(3)
    a_response = input('''What thinking styles did you engage in?
Use questions below to respond to the automatic thoughts
How much do you believe each response (0-100%)?''')
    time.sleep(3)
    outcome = input('''How much do you now believe your Automatic Thoughts (0-100%)?
What emotions do you now feel? At what intensity?''')
    time.sleep(3)
    print('''
An important part of self help is self care. 

Sometimes self-care is bubble baths and sometimes self-care is admitting you're self-sabotaging and 
learning how not to. It's learning how to stop the toxic cycles in your life and it's fuzzy blankets. 
It's forcing yourself to shower because you're depressed and haven't bathed in a week, and it's curling up with a good book. 

Self-care is about meeting *your* needs and because everyone is different and has different needs, 
and different needs on different days, - self-care is not one-size-fits-all.

It changes for the person and it changes on the day, but ultimately it just means caring for yourself 
and taking care of yourself with actions that reflect that. Not just physically but mentally and emotionally.

Here are a few journaling prompts for Self-Love: (you can take it one day at a time)

1. What is your biggest struggle with loving yourself?
2. Get rid of a limiting belief that you have about yourself or your abilities.
3. What good habit do you want to begin this month?
4. What’s one compliment you struggle to accept about yourself?
5. What do you need to start saying “yes” to?
6. What do you need to forgive yourself for?
7. Name a thing that you love about your body and then a thing you love about your personality.
8. Where in your life do you need to slow down and take your time?
9. What’s something that you need to get rid of?
10. How can you set better boundaries in your life?
11. How would you describe yourself, in a loving way, to a stranger?
12. What things make you feel happy to be alive? And how can you add MORE of that into your life?
13. Take a selfie just as you are. Write a description of your face using loving words.
14. What would your younger self be proud of you for today?
15. What are you afraid to ask for? What do you need to speak up about?
16. What is the most loving thing you’ve ever done for yourself?
17. When was the last time you indulged yourself and how?
18. What’s one change in your life that you can make for more happiness?
19. How are you making the world a better place? Self love is about acknowledging your talents, 
your power, and your worth as a human being. Maybe you’re raising (or have raised) kind and 
compassionate kids, or you’re kind and compassionate to others, or you share your art or your 
writing or you’re positive or caring – all things that make the world better.
20. How can you give yourself a break today? [Mentally, physically, or emotionally]
21. What’s something that you’re working on believing that you deserve?
22. What things make you feel bad, but you find yourself doing them anyway?
23. What does your support system look like? How can you make it stronger?
24. What’s something you wish someone would say to you?
25. What things are you really really good at? Bonus points if you can name FIVE things!
26. What parts of yourself are you ashamed of? What does your shadow self-look like?
27. What’s one choice you can make right now that your future self will thank you for?
28. Who are your role models and what qualities do you (already) share with them?
29. What words or beliefs do you (want to) live your life by?
30. What labels, negative and positive, do you assign yourself?
31. Going forward, how can you commit to loving yourself every day?''')

  elif x == 9: #getting unstuck 
    print(''' GETTING UNSTUCK:

Do you feel like you are stuck inside this quicksand of a life? Or that maybe everyone just seems way ahead of you
and you just can't seem to keep up with your life the way everyone else has it under control. Or maybe you feel stagnant, 
stuck in place like a statue glued to you foundations. It is totally okay to feel this way. No matter what, nobody's life is as perfect
and uninterrepted as how they might make it seem.
Here are some reasons why you could feel like you are stuck in place and how to deal with these:

1. A lot of people feel stuck at times because we feel like our life shouldn't be the way it is. We feel that life should
be different than it is. 

In these times, it is important to have faith. Faith doesn't only mean a religious belief in god. It is great if you have faith in god, in such times
it is important to remember that the powers that be have something good and meaningful in store for us and we should just keep going on our path like the way we 
have been. In case, you are not a person of religious faith, it is completely fine. You must believe in yourself, you must believe that over time, your life will
also turn into a steadily flowing river. You must remember that you are human and such problems are a part of life, if it has arrived, the adversity will also leave, 
you must believe that no matter what happens, you will keep going on the path you alkready have choisen for youself and you must believe that the decisions you are 
making, slowly, but surely will bring a drastic change to your life. That is something you can look forward to.

2. We often feel stuck because of our various insecurities.
When we compare ourselves to our past or another person even. 

3. Your mind is attempting to push, control and manipulate you when you wish to be secure, loved and remarkable. WHen you feel like you are inferiour to others.

4. You feel that if you could just control your life, it would all be well.

5. You feel like everyone else is able to control what they do and when they do it but you yourself 
don't have any authority over your schedule, like you are slave to the circumstances. You attend meetings when your boss or mentor feels like it.
You submit projects on the preset deadline which din't insorporate into it whether you wanted  to do so or not.

6. You may even think that there is no hope for any change. When you feel like you can't go anywhere from this.
Like you've done it all and there is nothing left for you to do, or nothing left that serves your perposes or that you would feind interst in.

7. You feel like you are stuck in this endless cycle of your despicable job or that you are completely clueless about what to do with your life.

WHAT CAN YOU DO ABOUT THIS?

 There are quite a few solutions to this problem:

  1. Thoughts create your situation. They frame how you see the world. They are, in fact, the foundation of your current paradigm. 
  It’s so easy to use your thoughts to create a convenient narrative about why you're worthless and can’t go anywhere.
  people do it all the time, but there is something you can do. However, you won't be able to move forward if you keepo telling yourself tha you are 'stuck'!
  Negative thinking is a slippery slope...

  In a way, it’s adaptive. It keeps you in place, in your perceived safety. When you think yourself into a corner, you don’t have to go anywhere. 
  The ego wants that because your ego wants to keep you safe and secure. 
  A lot of times when we feel hopeless, there is an underlying fear that our brain just doesn't want us to move through, it feels like it's portecting you,
  however, it's not. There is always a light at the end of the tunnel. Go find it!

  2. You must acknowledge that you are the creator of your own reality, you created these thoughts by thinking about how stuck you are.....
  What if you think about the good things? Wouldn't you reality turn into good things? You might start to see possibilites!

  3. Make sure you’re taking care of yourself. If you’re tired and dehydrated, it’s only natural to think negative thoughts and begin to feel so lost in life. 
  The body and the mind are related, and your brain will pull from your physical state to think thoughts that it feels relate to your physical feelings.

  4. If you feel like you are stuck because of an unending job...There has to be something about your job that brings you joy.
  Even if it’s the small amounts of time that you get by yourself when you’re cleaning up.Could you use that time to create a new future for yourself? 
  Could that be your own private space to mentally create a new reality instead of repeating the 'Im stuck" loop in your head? Likewise, 
  focus your full attention on these joyful tasks. There are going to be times in your work that you hate. 
  Thankfully, you get to choose your attitude during the times that you enjoy.

  5. Always look for other opportunities to figure out what to do with your life. This might see shady/risky to some people, but it could be realistic if you believe so.
  You are a valuable human being with real skills. You should always be scanning the horizon to see how you can best offer those skills.
  You’re not required to be in one job until the end of time. You can go somewhere else. It’s often an outdated mental model, likely handed down to you when you were young, 
  that is telling you that you can’t go anywhere. You can. It may not be a perfect opportunity, but you can make incremental moves in your life. 
  Before you know it, you’re doing work you love!

  6. The reality is this: a life plan doesn't just magically materialize in the blink of an eye.

  Your career path is a series of steps, a process of discovery.

  But how do you start the process?

  You start with a question that's easier to answer.

  How do I choose a job?
  A job is smaller than a career. That's obvious.

  But how do you go about picking one?

  Well, what are your talents?

  What do you enjoy doing?

  Going back to the child analogy, what made your eyes light up when you were a kid?

  Do you even remember?
  If you're stuck and can't think of anything, talk to the people who know you best--your parents, your friends--or maybe your neighbors or even your current coworkers, 
  if you're working in a job that you're trying to get away from.

  7. Sometimes, it is also better to let it go. When you feel stuck, notice that it's not thge first time, humans feel this way quite often. What helped you the last time?
  Or, just let these feelings go, focus on today, not tomorrow nd yesterday.


Sometimes, we even feel stuck because we just have too much to do and no one to talk to about this, 
or no one who you think will understand or just the fear of not talking to people.
If you feel this way, you could start to keep diary entries. Otherwise, we are also here to help you and listen to you.
Do you wish to type in what you feel?
  ''')
    stuckq = str(input("Do you wish to talk about it?(We promise, we would only listen, not judge): "))
    time.sleep(3)
    if stuckq == 'Yes' or stuckq == 'yes' or stuckq == 'YES':
      typespace = str(input('Go ahead...we are listening :)   : '))
      time.sleep(3)
      print("Thank you so much for sharing with us, in case you still don't feel better, it is a good idea to contact a proffesional, fill the form below to book a free consultation :)")
    else:
      time.sleep(3)
      print('''That's okay, however, in case you don't feel better in a few weeks, please feel free to contact us and book a counselling session with one of our specialists
            through the form below''')

  elif x == 10: #student life
    print('''STUDENT LIFE:

In case you are a student, it is totally understandable that you are under stress. It even shows how much you care about your studies.
But very often this nervousness turns into full blown stress and wreaks havoc on our minds. 
There are multiple factors which could (even unknowingly) could -produce stress in a student's fragile and developing mind, These are a few of them:
  1. struggling with your mental health
  2. loneliness, homesickness or relationship difficulties (especially when you aren't close to home.)
  3.finding it hard to save money or deal with debt
  4.not knowing how to balance work and study
  5.worrying about revising for exams
  6.struggling with writing essays or dissertations
  7.feeling unsure about what to do after graduation
  8.harmful use of, or withdrawal from, alcohol or drugs.

In case you are struggling with any of these issues, it is totally understandable that you are under stress. Even if this isn't the case,
considering that fact that most students go through puberty, the stress could just be a result of your growning hormones or the imbalance between them
which is nothing to be ashamed of:)
   
Here are a few ways to cope with this stress:

  1. Try out some mindfulness exercises. There is a lot of evidence to suggest these can be really helpful, especially for managing stress.
  Here are a few execises you could try:
  https://www.youtube.com/watch?v=O-6f5wQXSu8 (meditation)
  https://www.youtube.com/watch?v=tc0oVElWR5I (Brief mindful breathing for anxiety)

  2. Try using a planner. This can help to keep track of deadlines and key commitments and organise your study.

  3. Take time out to relax. Getting away from your desk, even for short periods of time, can help keep you calm.

  4. Keep an eye on social commitments to avoid overloading your schedule around deadlines and exams.

  5. Try online support and apps. There are lots of apps and websites available that can help you to manage your stress levels, 
  such as those offering a daily meditation or mindfulness practice. Here are some apps you could try:

   Insight timer
   Smiling Mind
   MyLife Meditation
   UCLA mindful
   Healthy Minds program
   Headspace
   Aura 
   MyLife

  6.When your loan drops into your bank account, it will almost certainly be one of the largest sums of money you have ever seen. 
  However, by the time you have paid your rent, and any university dues, it will be a LOT smaller. By the end of term, you may well find that 
  you are struggling not to be overdrawn. So before you spend anything, draw up a budget

  7.You need to eat (reasonably) well to remain healthy. 
  At the start of term, it is easy to get sucked into buying lunches out, or coffee, leaving you surviving on baked beans towards the end of term.
  Instead, try to buy in bulk and cook or plan ahead so that you can save a bit of money on food. It is also worth finding out when your local shops reduce food that is 
  close to its sell-by date, because this can be a very good time to buy staples like bread. 
  Especially if you share with friends, this can be a good way to buy cheaply but eat well.

  8.There is a lot of rhetoric about how you will meet your ‘lifelong friends’ at university. This puts pressure on people to make those friendships IMMEDIATELY, 
  which can be very stressful. Many people struggle in their first year because they feel that they haven’t yet made good friendships and they might get left behind.
  Don’t worry.

  In reality, most people don’t make those close friendships until their second or third year, when they have relaxed a bit and got to know people better.

  What’s more, this means that a lot of friendships form and break up again in the first couple of years, especially when one or other of you is under pressure. 
  Don’t worry too much about this.
  Not every friendship in your life—at university or not—is going to last forever, and nor would you want it to do so.
  
  9. Never give in to peer pressure. If you find that you are uncomfortable about doing something, don’t do it.
  If your friends put pressure on you to do it, then they are probably not your friends.

  10. Students in higher years can be a good source of advice.
  Senior students are a great source of advice. 
  They know your tutors and supervisors, they know the course material, and they know the town or university/school.
  They can tell you who will accept late submissions and who won’t, which books or journals are essential reading, 
  where the academic shortcuts lie, and even which parts of town are safe to live in.

  Your university may provide opportunities to get to know them—but if not, go and find them and introduce yourself. 
  They may also have a social media group that you can join, so that you can ask questions when you need.

In case you still feel like this stress is never ending and is turning into a huge source of burden for you, feel free to fill the following form and contact one of
our mental health experts. No matter what, we are there for you :)
''')

  elif x == 11: #forgiveness
    print(''' FORGIVENESS:

  Is it time to forgive?''')
    time.sleep(3)
    heal = input("are you ready to heal from this? ")

    if heal == "Yes" or heal == "yes" or heal == "YES":
      time.sleep(3)
      print('''it's time to forgive, yourself too. 
    forgiveness isn't about excusing bad behavior. it's about freeing yourself.''')
    else:
      time.sleep(3)
      print('''forgive them because you deserve to heal from it. 
    ''')
      print('''You don’t know how heavy it is until you let it go.
A grudge is like a pain that you’ve had for so long that you barely feel it anymore 
but when it’s gone you don’t know how you managed to live with it.

Write down all of the grudges you're holding onto. All of the things that you're still pissed 
about no matter how long ago they happened or how small they were.  
The things you have carried within yourself.
Go down the list of those grudges and examine them. Some of them will be easy to let go. 
You acknowledge the hurt and why it hurt and then you let it go and move on. Others will take a lot 
of work and examination and journaling and talking, but once you do that, once you let go…

It will feel so unbelievably good.
Forgiving yourself is ridiculously hard. There’s all those should haves 
and could haves and we wish we had done better, known better, listened and acted better. 
It’s so easy to place the blame on ourselves and internalize everything. The work to find forgiveness, 
to get through those feelings, is worth it. The energy to let it go is worth it.
    ''')
    
  elif x == 12:
    print(''' I JUST DONT FEEL OKAY:

  It's ok if you don't want to go into whatever you're going through 
  at the moment or you just can't get yourself to describe it.

  If today is hard:
1. Be open about how you are feeling.
2. Get your favorite take-out
3. Get some love from the people around you.
4. Have a movie marathon.
5. Curl up in bed with a good book.
6. Do some-thing kind for your community.
7. Open your window and get fresh air. 
8. Pamper yourself with a mini spa day.
9. Put on headphones and journal your feelings.
10. Take a break from social media.
11. Be gentle sweet, loving and show compassion to yourself. 
12. Watch something that makes you laugh. 
13. Take a deep breath and relax your shoulders. 
14. Give yourself permission to cry it out. 
15. Do things that recharge your internal battery. 
16. Find a positive outlet for your emotions.

  here's something to help you feel better,
  https://thenicestplace.net/?_kx=TWnxtPC3OnFKlTeCKzgkTMNvCbPjnGKzitOM_mxaYZ0%3D.PFrrZ]H&utm_source=newsletter&utm_medium=email&utm_campaign=062621_doyouhug_huggingvideo

  ''')

  elif x == 13: #other #input
    print(''' OTHER:  
  ''')
    other = input("what is it that we can help you with today? ")

  elif x == 0: #exit main library
    break

end()

print('''Here are a few important questions you can ask yourself to check on your mental health.
Take care of yourself. You're going to be ok:

1. How am I feeling (physically and mentally)
2. When did I last eat a whole meal?
3. When did I last drink water?
4. How long have I spent on my phone today?
5. When did I last breathe deeply?
6. When did I last talk to someone about my feelings?
7. When did I last go outside?
8. What can I celebrate today?
9. When did I last take a shower (or bath)?
10. What is taking up most of my headspace?
11. Am I tired?
12. When did I last do a kind thing for someone else?
13. What can I do that will bring me joy?
''') #mental health check